<a href="https://colab.research.google.com/github/SANAD343/Complete-Machine-Learning/blob/main/Naive_Bayes_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Baye's Machine Learning Algorithms Implementation

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X,y=load_iris(return_X_y=True)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
X_train.shape

(105, 4)

# Implement the GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb=GaussianNB()

In [ ]:
gnb.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [ ]:
print(accuracy_score(y_pred,y_test))

1.0


In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [20]:
sn=pd.read_csv('/content/sample_data/Social_Network_Ads[1].csv')

In [21]:

sn

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [22]:
sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [23]:
sn.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [24]:
sn.duplicated().sum()

33

In [25]:
sn.drop_duplicates(inplace=True)

In [26]:
sn.duplicated().sum()

0

# creating the independent and dependent variable

In [27]:
x=sn.iloc[:,:-1].values

In [28]:
x.shape

(367, 2)

In [29]:
y=sn.iloc[:,-1].values

In [30]:
y.shape

(367,)

# Perform the train test split

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

# Implement the  Linear regression

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
reg=LinearRegression()

In [35]:
reg.fit(x_train,y_train)

LinearRegression()

In [36]:
m=reg.coef_

In [37]:
c=reg.intercept_

In [39]:
X=52
Y=m*X+c
Y

array([ 0.50278826, -0.89336186])

In [40]:
y_pred=reg.predict(x_test)

In [41]:
reg.score(x_test,y_test)

0.47438312338709787

In [42]:
y_pred

array([ 1.0950045 ,  0.19524257,  0.54387788,  0.37379302, -0.22330145,
        0.14226506,  0.38489286,  0.11541232,  1.05873303,  0.1691178 ,
        0.4738041 ,  0.28583491,  0.41152044,  0.45362328,  0.42307059,
       -0.17878954,  0.39885208,  0.17853653,  0.46522592,  0.3451466 ,
        0.56725583,  0.58228077,  0.39145219,  0.55722171,  0.12029056,
        0.46007003,  0.13139039,  0.64949516,  0.06467881,  0.43226416,
        0.24788234,  0.12769044,  1.06433923,  0.54589672,  0.75915013,
        0.95608772,  0.38298659,  0.1905895 ,  0.3412215 ,  0.39610527,
        0.47105729, -0.03830424,  0.52930326,  0.35445275,  0.37188676,
        1.21984947,  0.60509583, -0.06969747, -0.14083696, -0.28715363,
       -0.12435609,  0.47952289, -0.23619496,  0.28392865,  0.61546769,
        0.04427283,  0.11087182,  0.40625197,  0.31554705,  0.02745421,
        0.64506724,  0.41639867,  0.44252344,  0.30910029, -0.13248394,
       -0.30565335,  1.01635254,  0.27198827, -0.05310401,  0.83

# Implement the GaussianNB

In [43]:
from sklearn.naive_bayes import GaussianNB

In [44]:
gnb=GaussianNB()

In [45]:
gnb.fit(x_train,y_train)

GaussianNB()

In [46]:
y_predicted=gnb.predict(x_test)

In [47]:
y_predicted

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0])

In [48]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_test,y_predicted)

0.9324324324324325

In [50]:
gnb.score(x_test,y_test)

0.9324324324324325

In [51]:
gnb.score(x_train,y_train)

0.8771331058020477