<a href="https://colab.research.google.com/github/SANAD343/Complete-Machine-Learning/blob/main/K_Nearest_Neighbor(KNN)_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/content/sample_data/caesarian.csv.xls")

In [3]:
df.head(5)

Age  Delivery number  Delivery time  Blood of Pressure  Heart Problem  \
0   22                1              0                  2              0   
1   26                2              0                  1              0   
2   26                2              1                  1              0   
3   28                1              0                  2              0   
4   22                2              0                  1              0   

   Caesarian  
0          0  
1          1  
2          0  
3          0  
4          1

In [4]:
df.isnull().sum()

Age                  0
Delivery number      0
Delivery time        0
Blood of Pressure    0
Heart Problem        0
Caesarian            0
dtype: int64

In [5]:
df.isnull().any(axis=0)

Age                  False
Delivery number      False
Delivery time        False
Blood of Pressure    False
Heart Problem        False
Caesarian            False
dtype: bool

In [6]:
df.duplicated().sum()

4

In [7]:
x=df.iloc[:,:-1].values

In [8]:
x.shape

(80, 5)

In [9]:
y=df.iloc[:,-1].values

In [10]:
y.shape

(80,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
classifier=KNeighborsClassifier(n_neighbors=5, p=2)

In [15]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred=classifier.predict(x_test)

In [17]:
len(x_test)

16

In [18]:
y_pred

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [19]:
y_test

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0])

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[4, 1],
       [4, 7]])

In [22]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.6875

In [23]:
classifier.score(x_test,y_test)

0.6875